// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authentication {

  /// <summary>Holder for reflection information generated from AuthType.proto</summary>
  public static partial class AuthTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for AuthType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5BdXRoVHlwZS5wcm90bxIOQXV0aGVudGljYXRpb24qFgoIQXV0aFR5cGUS",
            "CgoGUGhpS2V5EABiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Authentication.AuthType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum AuthType {
    [pbr::OriginalName("PhiKey")] PhiKey = 0,
  }

  #endregion

}

#endregion Designer generated code
