// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packets/ChatHistoryPacket.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat {

  /// <summary>Holder for reflection information generated from Packets/ChatHistoryPacket.proto</summary>
  public static partial class ChatHistoryPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/ChatHistoryPacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatHistoryPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9QYWNrZXRzL0NoYXRIaXN0b3J5UGFja2V0LnByb3RvEgRDaGF0Gh9QYWNr",
            "ZXRzL0NoYXRNZXNzYWdlUGFja2V0LnByb3RvIkIKEUNoYXRIaXN0b3J5UGFj",
            "a2V0Ei0KDENoYXRNZXNzYWdlcxgBIAMoCzIXLkNoYXQuQ2hhdE1lc3NhZ2VQ",
            "YWNrZXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Chat.ChatMessagePacketReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.ChatHistoryPacket), global::Chat.ChatHistoryPacket.Parser, new[]{ "ChatMessages" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChatHistoryPacket : pb::IMessage<ChatHistoryPacket> {
    private static readonly pb::MessageParser<ChatHistoryPacket> _parser = new pb::MessageParser<ChatHistoryPacket>(() => new ChatHistoryPacket());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatHistoryPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatHistoryPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatHistoryPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatHistoryPacket(ChatHistoryPacket other) : this() {
      chatMessages_ = other.chatMessages_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatHistoryPacket Clone() {
      return new ChatHistoryPacket(this);
    }

    /// <summary>Field number for the "ChatMessages" field.</summary>
    public const int ChatMessagesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Chat.ChatMessagePacket> _repeated_chatMessages_codec
        = pb::FieldCodec.ForMessage(10, global::Chat.ChatMessagePacket.Parser);
    private readonly pbc::RepeatedField<global::Chat.ChatMessagePacket> chatMessages_ = new pbc::RepeatedField<global::Chat.ChatMessagePacket>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Chat.ChatMessagePacket> ChatMessages {
      get { return chatMessages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatHistoryPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatHistoryPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!chatMessages_.Equals(other.chatMessages_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= chatMessages_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      chatMessages_.WriteTo(output, _repeated_chatMessages_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += chatMessages_.CalculateSize(_repeated_chatMessages_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatHistoryPacket other) {
      if (other == null) {
        return;
      }
      chatMessages_.Add(other.chatMessages_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            chatMessages_.AddEntriesFrom(input, _repeated_chatMessages_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
