// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Credentials/ServerCredential.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authentication {

  /// <summary>Holder for reflection information generated from Credentials/ServerCredential.proto</summary>
  public static partial class ServerCredentialReflection {

    #region Descriptor
    /// <summary>File descriptor for Credentials/ServerCredential.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerCredentialReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJDcmVkZW50aWFscy9TZXJ2ZXJDcmVkZW50aWFsLnByb3RvEg5BdXRoZW50",
            "aWNhdGlvbhoXUGFja2V0cy9BdXRoVHlwZXMucHJvdG8icwoQU2VydmVyQ3Jl",
            "ZGVudGlhbBIrCghBdXRoVHlwZRgBIAEoDjIZLkF1dGhlbnRpY2F0aW9uLkF1",
            "dGhUeXBlcxIQCghVc2VybmFtZRgCIAEoCRIQCghQYXNzd29yZBgDIAEoCRIO",
            "CgZCYW5uZWQYBCABKAhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Authentication.AuthTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Authentication.ServerCredential), global::Authentication.ServerCredential.Parser, new[]{ "AuthType", "Username", "Password", "Banned" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ServerCredential : pb::IMessage<ServerCredential> {
    private static readonly pb::MessageParser<ServerCredential> _parser = new pb::MessageParser<ServerCredential>(() => new ServerCredential());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerCredential> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authentication.ServerCredentialReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerCredential() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerCredential(ServerCredential other) : this() {
      authType_ = other.authType_;
      username_ = other.username_;
      password_ = other.password_;
      banned_ = other.banned_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerCredential Clone() {
      return new ServerCredential(this);
    }

    /// <summary>Field number for the "AuthType" field.</summary>
    public const int AuthTypeFieldNumber = 1;
    private global::Authentication.AuthTypes authType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Authentication.AuthTypes AuthType {
      get { return authType_; }
      set {
        authType_ = value;
      }
    }

    /// <summary>Field number for the "Username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Banned" field.</summary>
    public const int BannedFieldNumber = 4;
    private bool banned_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Banned {
      get { return banned_; }
      set {
        banned_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerCredential);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerCredential other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AuthType != other.AuthType) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (Banned != other.Banned) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AuthType != 0) hash ^= AuthType.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Banned != false) hash ^= Banned.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AuthType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AuthType);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (Banned != false) {
        output.WriteRawTag(32);
        output.WriteBool(Banned);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AuthType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AuthType);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Banned != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerCredential other) {
      if (other == null) {
        return;
      }
      if (other.AuthType != 0) {
        AuthType = other.AuthType;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Banned != false) {
        Banned = other.Banned;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            authType_ = (global::Authentication.AuthTypes) input.ReadEnum();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 32: {
            Banned = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
