// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Credentials/ServerCredentialStore.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authentication {

  /// <summary>Holder for reflection information generated from Credentials/ServerCredentialStore.proto</summary>
  public static partial class ServerCredentialStoreReflection {

    #region Descriptor
    /// <summary>File descriptor for Credentials/ServerCredentialStore.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerCredentialStoreReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidDcmVkZW50aWFscy9TZXJ2ZXJDcmVkZW50aWFsU3RvcmUucHJvdG8SDkF1",
            "dGhlbnRpY2F0aW9uGiJDcmVkZW50aWFscy9TZXJ2ZXJDcmVkZW50aWFsLnBy",
            "b3RvIroBChVTZXJ2ZXJDcmVkZW50aWFsU3RvcmUSSwoLQ3JlZGVudGlhbHMY",
            "ASADKAsyNi5BdXRoZW50aWNhdGlvbi5TZXJ2ZXJDcmVkZW50aWFsU3RvcmUu",
            "Q3JlZGVudGlhbHNFbnRyeRpUChBDcmVkZW50aWFsc0VudHJ5EgsKA2tleRgB",
            "IAEoCRIvCgV2YWx1ZRgCIAEoCzIgLkF1dGhlbnRpY2F0aW9uLlNlcnZlckNy",
            "ZWRlbnRpYWw6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Authentication.ServerCredentialReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Authentication.ServerCredentialStore), global::Authentication.ServerCredentialStore.Parser, new[]{ "Credentials" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ServerCredentialStore : pb::IMessage<ServerCredentialStore> {
    private static readonly pb::MessageParser<ServerCredentialStore> _parser = new pb::MessageParser<ServerCredentialStore>(() => new ServerCredentialStore());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerCredentialStore> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authentication.ServerCredentialStoreReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerCredentialStore() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerCredentialStore(ServerCredentialStore other) : this() {
      credentials_ = other.credentials_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerCredentialStore Clone() {
      return new ServerCredentialStore(this);
    }

    /// <summary>Field number for the "Credentials" field.</summary>
    public const int CredentialsFieldNumber = 1;
    private static readonly pbc::MapField<string, global::Authentication.ServerCredential>.Codec _map_credentials_codec
        = new pbc::MapField<string, global::Authentication.ServerCredential>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::Authentication.ServerCredential.Parser), 10);
    private readonly pbc::MapField<string, global::Authentication.ServerCredential> credentials_ = new pbc::MapField<string, global::Authentication.ServerCredential>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::Authentication.ServerCredential> Credentials {
      get { return credentials_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerCredentialStore);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerCredentialStore other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Credentials.Equals(other.Credentials)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Credentials.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      credentials_.WriteTo(output, _map_credentials_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += credentials_.CalculateSize(_map_credentials_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerCredentialStore other) {
      if (other == null) {
        return;
      }
      credentials_.Add(other.credentials_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            credentials_.AddEntriesFrom(input, _map_credentials_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
