// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packets/Gender.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Trading {

  /// <summary>Holder for reflection information generated from Packets/Gender.proto</summary>
  public static partial class GenderReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/Gender.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GenderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQYWNrZXRzL0dlbmRlci5wcm90bxIHVHJhZGluZyo8CgZHZW5kZXISDwoL",
            "R0VOREVSX05PTkUQABIOCgpHRU5EUl9NQUxFEAESEQoNR0VOREVSX0ZFTUFM",
            "RRACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Trading.Gender), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Gender {
    [pbr::OriginalName("GENDER_NONE")] None = 0,
    [pbr::OriginalName("GENDR_MALE")] GendrMale = 1,
    [pbr::OriginalName("GENDER_FEMALE")] Female = 2,
  }

  #endregion

}

#endregion Designer generated code
