// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packets/Quality.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Trading {

  /// <summary>Holder for reflection information generated from Packets/Quality.proto</summary>
  public static partial class QualityReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/Quality.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QualityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVQYWNrZXRzL1F1YWxpdHkucHJvdG8SB1RyYWRpbmcqbAoHUXVhbGl0eRIJ",
            "CgVBd2Z1bBAAEggKBFBvb3IQARIKCgZOb3JtYWwQAhIICgRHb29kEAMSDQoJ",
            "RXhjZWxsZW50EAQSDgoKTWFzdGVyd29yaxAFEg0KCUxlZ2VuZGFyeRAGEggK",
            "BE5vbmUQB2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Trading.Quality), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Quality {
    [pbr::OriginalName("Awful")] Awful = 0,
    [pbr::OriginalName("Poor")] Poor = 1,
    [pbr::OriginalName("Normal")] Normal = 2,
    [pbr::OriginalName("Good")] Good = 3,
    [pbr::OriginalName("Excellent")] Excellent = 4,
    [pbr::OriginalName("Masterwork")] Masterwork = 5,
    [pbr::OriginalName("Legendary")] Legendary = 6,
    [pbr::OriginalName("None")] None = 7,
  }

  #endregion

}

#endregion Designer generated code
