// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packets/SyncTradesPacket.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Trading {

  /// <summary>Holder for reflection information generated from Packets/SyncTradesPacket.proto</summary>
  public static partial class SyncTradesPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/SyncTradesPacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SyncTradesPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5QYWNrZXRzL1N5bmNUcmFkZXNQYWNrZXQucHJvdG8SB1RyYWRpbmcaGFBh",
            "Y2tldHMvVHJhZGVQcm90by5wcm90byI3ChBTeW5jVHJhZGVzUGFja2V0EiMK",
            "BlRyYWRlcxgBIAMoCzITLlRyYWRpbmcuVHJhZGVQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Trading.TradeProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Trading.SyncTradesPacket), global::Trading.SyncTradesPacket.Parser, new[]{ "Trades" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SyncTradesPacket : pb::IMessage<SyncTradesPacket> {
    private static readonly pb::MessageParser<SyncTradesPacket> _parser = new pb::MessageParser<SyncTradesPacket>(() => new SyncTradesPacket());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SyncTradesPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Trading.SyncTradesPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncTradesPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncTradesPacket(SyncTradesPacket other) : this() {
      trades_ = other.trades_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncTradesPacket Clone() {
      return new SyncTradesPacket(this);
    }

    /// <summary>Field number for the "Trades" field.</summary>
    public const int TradesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Trading.TradeProto> _repeated_trades_codec
        = pb::FieldCodec.ForMessage(10, global::Trading.TradeProto.Parser);
    private readonly pbc::RepeatedField<global::Trading.TradeProto> trades_ = new pbc::RepeatedField<global::Trading.TradeProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Trading.TradeProto> Trades {
      get { return trades_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SyncTradesPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SyncTradesPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!trades_.Equals(other.trades_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= trades_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      trades_.WriteTo(output, _repeated_trades_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += trades_.CalculateSize(_repeated_trades_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SyncTradesPacket other) {
      if (other == null) {
        return;
      }
      trades_.Add(other.trades_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            trades_.AddEntriesFrom(input, _repeated_trades_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
