// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packets/TradeFailureReason.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Trading {

  /// <summary>Holder for reflection information generated from Packets/TradeFailureReason.proto</summary>
  public static partial class TradeFailureReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/TradeFailureReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TradeFailureReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBQYWNrZXRzL1RyYWRlRmFpbHVyZVJlYXNvbi5wcm90bxIHVHJhZGluZyq8",
            "AQoSVHJhZGVGYWlsdXJlUmVhc29uEg0KCVNlc3Npb25JZBAAEggKBFV1aWQQ",
            "ARIXChNJbnRlcm5hbFNlcnZlckVycm9yEAISFQoRT3RoZXJQYXJ0eU9mZmxp",
            "bmUQAxIaChZPdGhlclBhcnR5RG9lc05vdEV4aXN0EAQSEgoOQWxyZWFkeVRy",
            "YWRpbmcQBRIVChFUcmFkZURvZXNOb3RFeGlzdBAGEhYKEk5vdEFjY2VwdGlu",
            "Z1RyYWRlcxAHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Trading.TradeFailureReason), }, null));
    }
    #endregion

  }
  #region Enums
  public enum TradeFailureReason {
    [pbr::OriginalName("SessionId")] SessionId = 0,
    [pbr::OriginalName("Uuid")] Uuid = 1,
    [pbr::OriginalName("InternalServerError")] InternalServerError = 2,
    [pbr::OriginalName("OtherPartyOffline")] OtherPartyOffline = 3,
    [pbr::OriginalName("OtherPartyDoesNotExist")] OtherPartyDoesNotExist = 4,
    [pbr::OriginalName("AlreadyTrading")] AlreadyTrading = 5,
    [pbr::OriginalName("TradeDoesNotExist")] TradeDoesNotExist = 6,
    [pbr::OriginalName("NotAcceptingTrades")] NotAcceptingTrades = 7,
  }

  #endregion

}

#endregion Designer generated code
