// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packets/UpdateTradeStatusPacket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Trading {

  /// <summary>Holder for reflection information generated from Packets/UpdateTradeStatusPacket.proto</summary>
  public static partial class UpdateTradeStatusPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/UpdateTradeStatusPacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UpdateTradeStatusPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVQYWNrZXRzL1VwZGF0ZVRyYWRlU3RhdHVzUGFja2V0LnByb3RvEgdUcmFk",
            "aW5nIowBChdVcGRhdGVUcmFkZVN0YXR1c1BhY2tldBIRCglTZXNzaW9uSWQY",
            "ASABKAkSDAoEVXVpZBgCIAEoCRIPCgdUcmFkZUlkGAMgASgJEhAKCEFjY2Vw",
            "dGVkGAQgASgIEhoKEk90aGVyUGFydHlBY2NlcHRlZBgFIAEoCBIRCglDYW5j",
            "ZWxsZWQYBiABKAhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Trading.UpdateTradeStatusPacket), global::Trading.UpdateTradeStatusPacket.Parser, new[]{ "SessionId", "Uuid", "TradeId", "Accepted", "OtherPartyAccepted", "Cancelled" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UpdateTradeStatusPacket : pb::IMessage<UpdateTradeStatusPacket> {
    private static readonly pb::MessageParser<UpdateTradeStatusPacket> _parser = new pb::MessageParser<UpdateTradeStatusPacket>(() => new UpdateTradeStatusPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateTradeStatusPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Trading.UpdateTradeStatusPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateTradeStatusPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateTradeStatusPacket(UpdateTradeStatusPacket other) : this() {
      sessionId_ = other.sessionId_;
      uuid_ = other.uuid_;
      tradeId_ = other.tradeId_;
      accepted_ = other.accepted_;
      otherPartyAccepted_ = other.otherPartyAccepted_;
      cancelled_ = other.cancelled_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateTradeStatusPacket Clone() {
      return new UpdateTradeStatusPacket(this);
    }

    /// <summary>Field number for the "SessionId" field.</summary>
    public const int SessionIdFieldNumber = 1;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Uuid" field.</summary>
    public const int UuidFieldNumber = 2;
    private string uuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TradeId" field.</summary>
    public const int TradeIdFieldNumber = 3;
    private string tradeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TradeId {
      get { return tradeId_; }
      set {
        tradeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Accepted" field.</summary>
    public const int AcceptedFieldNumber = 4;
    private bool accepted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Accepted {
      get { return accepted_; }
      set {
        accepted_ = value;
      }
    }

    /// <summary>Field number for the "OtherPartyAccepted" field.</summary>
    public const int OtherPartyAcceptedFieldNumber = 5;
    private bool otherPartyAccepted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool OtherPartyAccepted {
      get { return otherPartyAccepted_; }
      set {
        otherPartyAccepted_ = value;
      }
    }

    /// <summary>Field number for the "Cancelled" field.</summary>
    public const int CancelledFieldNumber = 6;
    private bool cancelled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Cancelled {
      get { return cancelled_; }
      set {
        cancelled_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateTradeStatusPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateTradeStatusPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SessionId != other.SessionId) return false;
      if (Uuid != other.Uuid) return false;
      if (TradeId != other.TradeId) return false;
      if (Accepted != other.Accepted) return false;
      if (OtherPartyAccepted != other.OtherPartyAccepted) return false;
      if (Cancelled != other.Cancelled) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (TradeId.Length != 0) hash ^= TradeId.GetHashCode();
      if (Accepted != false) hash ^= Accepted.GetHashCode();
      if (OtherPartyAccepted != false) hash ^= OtherPartyAccepted.GetHashCode();
      if (Cancelled != false) hash ^= Cancelled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SessionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionId);
      }
      if (Uuid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uuid);
      }
      if (TradeId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TradeId);
      }
      if (Accepted != false) {
        output.WriteRawTag(32);
        output.WriteBool(Accepted);
      }
      if (OtherPartyAccepted != false) {
        output.WriteRawTag(40);
        output.WriteBool(OtherPartyAccepted);
      }
      if (Cancelled != false) {
        output.WriteRawTag(48);
        output.WriteBool(Cancelled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uuid);
      }
      if (TradeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TradeId);
      }
      if (Accepted != false) {
        size += 1 + 1;
      }
      if (OtherPartyAccepted != false) {
        size += 1 + 1;
      }
      if (Cancelled != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateTradeStatusPacket other) {
      if (other == null) {
        return;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      if (other.TradeId.Length != 0) {
        TradeId = other.TradeId;
      }
      if (other.Accepted != false) {
        Accepted = other.Accepted;
      }
      if (other.OtherPartyAccepted != false) {
        OtherPartyAccepted = other.OtherPartyAccepted;
      }
      if (other.Cancelled != false) {
        Cancelled = other.Cancelled;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SessionId = input.ReadString();
            break;
          }
          case 18: {
            Uuid = input.ReadString();
            break;
          }
          case 26: {
            TradeId = input.ReadString();
            break;
          }
          case 32: {
            Accepted = input.ReadBool();
            break;
          }
          case 40: {
            OtherPartyAccepted = input.ReadBool();
            break;
          }
          case 48: {
            Cancelled = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
