// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packets/AuthFailureReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authentication {

  /// <summary>Holder for reflection information generated from Packets/AuthFailureReason.proto</summary>
  public static partial class AuthFailureReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/AuthFailureReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthFailureReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9QYWNrZXRzL0F1dGhGYWlsdXJlUmVhc29uLnByb3RvEg5BdXRoZW50aWNh",
            "dGlvbipaChFBdXRoRmFpbHVyZVJlYXNvbhIMCghBdXRoVHlwZRAAEg8KC0Ny",
            "ZWRlbnRpYWxzEAESDQoJU2Vzc2lvbklkEAISFwoTSW50ZXJuYWxTZXJ2ZXJF",
            "cnJvchADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Authentication.AuthFailureReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum AuthFailureReason {
    [pbr::OriginalName("AuthType")] AuthType = 0,
    [pbr::OriginalName("Credentials")] Credentials = 1,
    [pbr::OriginalName("SessionId")] SessionId = 2,
    [pbr::OriginalName("InternalServerError")] InternalServerError = 3,
  }

  #endregion

}

#endregion Designer generated code
