// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packets/AuthTypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authentication {

  /// <summary>Holder for reflection information generated from Packets/AuthTypes.proto</summary>
  public static partial class AuthTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/AuthTypes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdQYWNrZXRzL0F1dGhUeXBlcy5wcm90bxIOQXV0aGVudGljYXRpb24qGgoJ",
            "QXV0aFR5cGVzEg0KCUNsaWVudEtleRAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Authentication.AuthTypes), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum AuthTypes {
    [pbr::OriginalName("ClientKey")] ClientKey = 0,
  }

  #endregion

}

#endregion Designer generated code
