// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packets/FailureReason.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authentication {

  /// <summary>Holder for reflection information generated from Packets/FailureReason.proto</summary>
  public static partial class FailureReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/FailureReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FailureReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtQYWNrZXRzL0ZhaWx1cmVSZWFzb24ucHJvdG8SDkF1dGhlbnRpY2F0aW9u",
            "KlYKDUZhaWx1cmVSZWFzb24SDAoIQXV0aFR5cGUQABIPCgtDcmVkZW50aWFs",
            "cxABEg0KCVNlc3Npb25JZBACEhcKE0ludGVybmFsU2VydmVyRXJyb3IQA2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Authentication.FailureReason), }, null));
    }
    #endregion

  }
  #region Enums
  public enum FailureReason {
    [pbr::OriginalName("AuthType")] AuthType = 0,
    [pbr::OriginalName("Credentials")] Credentials = 1,
    [pbr::OriginalName("SessionId")] SessionId = 2,
    [pbr::OriginalName("InternalServerError")] InternalServerError = 3,
  }

  #endregion

}

#endregion Designer generated code
