// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packets/LoginFailureReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UserManagement {

  /// <summary>Holder for reflection information generated from Packets/LoginFailureReason.proto</summary>
  public static partial class LoginFailureReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for Packets/LoginFailureReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginFailureReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBQYWNrZXRzL0xvZ2luRmFpbHVyZVJlYXNvbi5wcm90bxIOVXNlck1hbmFn",
            "ZW1lbnQqTQoSTG9naW5GYWlsdXJlUmVhc29uEg0KCVNlc3Npb25JZBAAEg8K",
            "C0Rpc3BsYXlOYW1lEAISFwoTSW50ZXJuYWxTZXJ2ZXJFcnJvchABYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::UserManagement.LoginFailureReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LoginFailureReason {
    [pbr::OriginalName("SessionId")] SessionId = 0,
    [pbr::OriginalName("DisplayName")] DisplayName = 2,
    [pbr::OriginalName("InternalServerError")] InternalServerError = 1,
  }

  #endregion

}

#endregion Designer generated code
